name = "ctf/bank_12_free_pass"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "GPL-3.0"
description = "Aiken contracts for project 'ctf/bank_12_free_pass'"

[repository]
user = "invariant-0"
project = "bank_12_free_pass"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
